# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: your-web-app
  template:
    metadata:
      labels:
        app: your-web-app
    spec:
      containers:
        - name: your-web-app
          image: your-web-app:latest
          ports:
            - containerPort: 80
